name: Django CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
        pip install -r requirements.txt
      - name: Run tests
        run: | 
        python manage.py test